puts "Mastermind:"
puts "You have 10 attempts to guess the color code"
puts "Each guess recevies feedback accroding to the code below"
puts "Color Options:"
puts " -red"
puts " -blue"
puts " -yellow"
puts " -purple"
puts " -green"
puts " -orange"
puts " -brown"
puts " -white"
puts " -black"
puts "Code:"
puts "HOT - correct color and place"
puts "WARM - color is in the code in a different place"
puts "COLD - color is not anywhere in the code"
puts "BRRR - incorrect input"